name: Get Universal Sensor Catalog

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WL_V2_API_KEY: ${{ secrets.WL_V2_API_KEY }}
      WL_V2_API_URL: ${{ secrets.WL_V2_API_URL }}
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - name: fetch
        run: curl -X GET -o resources/universal-sensor-catalog.json $WL_V2_API_URL/universal-sensor-catalog?api-key=$WL_V2_API_KEY 
      - uses: stefanzweifel/git-auto-commit-action@v4
        file_pattern: resources/universal-sensor-catalog.json
        skip_dirty_check: false
