name: Update Java SDK Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update Java SDK Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install yq
        run: pip3 install yq
      - name: Update Java SDK Version
        run: sed -i 's/<version>.*\?<\/version>/<version>'`curl -s https://repo1.maven.org/maven2/com/weatherlink/weatherlink-v2-api-sdk/maven-metadata.xml | xq '.metadata.versioning.latest' | tr -d '"'`'<\/version>/g' _pages/java-sdk.md
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit changes
        run: |
          git commit -a -m "Update released dependency version in java-sdk" || echo "No changes to commit"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
